" This file automatically generated by
" /homes/fish/tlau/bin/yp-mailabbr.py

python import vimmail
cab send python vimmail.send("%")
cab abort python vimmail.abort("%")
iab tl tlau@cs.washington.edu
set tw=70 noshowmatch

